### PR TITLE
Getting started

### PR DESCRIPTION
**Pull request by gumdropsteve**
# Getting started
Purpose: Initial pull request to get `bsql-demos` repo started

## Goals
- update all current demos
  - to run on latest versions of BlazingSQL and RAPIDS
    - easily (i.e. "open, click 'run all', and it just works")
    - locally and in Google Colab
- determine a common format/theme for BlazingSQL demo notebooks
- present `bsql-demos` in accessible / understandable fashion 
  - e.g. README, intuitive layout, simple install process, quick how to guides/videos

### CODE REVIEW

**Comment by roaramburu** [comment]
Clean up the Titles, don't use the Word `Layout` and use BlazingSQL over bsql-demos.
image

Also, use Colab buttons like we have on the getting started of the pyblazing repo, not instructions on using the colab chrome extension.

image

**Comment by roaramburu** [comment]
I don't think we should include logos, it adds a lot of weird stuff and might not render the right way on different machines. If you do decide to use logos, make sure they have no backgrond and look good on whatever the color scheme would be (white/black/etc.), transparent backgrounds are ideal.
image

Change title to `Getting Started with BlazingSQL`
image

Use proper grammar and capitalization:
image

We require Pascal+ architecture, not necesarrily T4s.

Try Catch might not be ideal since the output is longer and more complicated looking.
image

I like a lot of this, but again, grammar/capitalization.
image

**Comment by roaramburu** [comment]
New cuDF has pretty print, so you just want to reference the gdf like a pandas and the rendering of the table will be more attractive.
image

Clean up grammar/caps:
image

**Comment by gumdropsteve** [comment]
@roaramburu please review

**Pull request merged**
