### PR TITLE
[REVIEW] BlazingSQL vs Spark Demo

### PR DESCRIPTION
**Pull request by gumdropsteve**
## BlazingSQL vs Spark Netflow Demo
In this notebook, we will cover: 
- How to set up BlazingSQL and the RAPIDS AI suite in Google Colab.
- How to read and query csv files with cuDF and BlazingSQL.
- How BlazingSQL compares against Apache Spark (analyzing over 20M records).

### CODE REVIEW

**Comment by gumdropsteve** [comment]
@roaramburu ready for review. Thanks.

**Comment by roaramburu** [comment]
Send colab link in comment thread to validate the jupyter notebook

**Comment by gumdropsteve** [comment]
https://colab.research.google.com/drive/1itjNQ2LsE1Zr1V9rmpDE83ymAJA90qSs

**Comment by roaramburu** [comment]
image
You need to have a `%%time` in the .show() cell b/c 142 ms is not how long pyspark took to run the query, but to build the execution plan.

**Comment by gumdropsteve** [comment]
Updated @roaramburu

#### Adjustments
- README.md 
- Spark query time

Colab link: https://colab.research.google.com/github/gumdropsteve/bsql-demos/blob/feature_vs_spark/vs_pyspark_netflow.ipynb

NOTE: README.md also updated to include Graphistry Netflow Demo button in #8

**Pull request merged**
